"""Shared LangSmith-related constants and aliases."""

from __future__ import annotations

LANGSMITH_API_KEY_ENV_VARS = ("LANGSMITH_API_KEY", "LANGCHAIN_API_KEY")
LANGSMITH_PROJECT_ENV_VARS = ("LANGSMITH_PROJECT", "LANGCHAIN_PROJECT")
LANGSMITH_API_URL_ENV_VARS = ("LANGSMITH_ENDPOINT", "LANGCHAIN_ENDPOINT")
LANGSMITH_TRACING_ENV_VARS = ("LANGSMITH_TRACING", "LANGCHAIN_TRACING_V2")
LANGSMITH_ENV_ALIAS_GROUPS = (
    LANGSMITH_API_KEY_ENV_VARS,
    LANGSMITH_PROJECT_ENV_VARS,
    LANGSMITH_API_URL_ENV_VARS,
    LANGSMITH_TRACING_ENV_VARS,
)
LANGSMITH_TRACE_SCALAR_TYPES = (str, int, float, bool, type(None))
LANGSMITH_TRACING_FALSE_VALUES = frozenset({"false", "0", "no", "off"})
LANGSMITH_MISSING = object()

__all__ = [
    "LANGSMITH_API_KEY_ENV_VARS",
    "LANGSMITH_API_URL_ENV_VARS",
    "LANGSMITH_ENV_ALIAS_GROUPS",
    "LANGSMITH_MISSING",
    "LANGSMITH_PROJECT_ENV_VARS",
    "LANGSMITH_TRACE_SCALAR_TYPES",
    "LANGSMITH_TRACING_ENV_VARS",
    "LANGSMITH_TRACING_FALSE_VALUES",
]
