"""
===============================================================================
File: harnessiq/tools/__init__.py

What this file does:
- Defines the package-level export surface for `harnessiq/tools` within the
  HarnessIQ runtime.
- Canonical tool primitives for Harnessiq.

Use cases:
- Import ADD_NUMBERS, ApprovalPolicy, BROWSER_CLICK, BROWSER_EXTRACT_CONTENT,
  BROWSER_FIND_ELEMENT, BROWSER_GET_CURRENT_URL from one stable package entry
  point.
- Read this module to understand what `harnessiq/tools` intends to expose
  publicly.

How to use it:
- Import from `harnessiq/tools` when you want the supported facade instead of
  reaching through deeper internal modules.

Intent:
- Keep the public surface for `harnessiq/tools` explicit, discoverable, and
  easier to maintain.
===============================================================================
"""

from harnessiq.shared.tools import (
    ADD_NUMBERS,
    BROWSER_CLICK,
    BROWSER_EXTRACT_CONTENT,
    BROWSER_FIND_ELEMENT,
    BROWSER_GET_CURRENT_URL,
    BROWSER_GET_TEXT,
    BROWSER_HOVER,
    BROWSER_NAVIGATE,
    BROWSER_PRESS_KEY,
    BROWSER_SCREENSHOT,
    BROWSER_SCROLL,
    BROWSER_SELECT_OPTION,
    BROWSER_TYPE,
    BROWSER_UPLOAD_FILE,
    BROWSER_USE_REQUEST,
    BROWSER_VIEW_HTML,
    BROWSER_WAIT_FOR_ELEMENT,
    CONTROL_PAUSE_FOR_HUMAN,
    ECHO_TEXT,
    EVALUATE_COMPANY,
    FILESYSTEM_APPEND_TEXT_FILE,
    FILESYSTEM_COPY_PATH,
    FILESYSTEM_GET_CURRENT_DIRECTORY,
    FILESYSTEM_LIST_DIRECTORY,
    FILESYSTEM_MAKE_DIRECTORY,
    FILESYSTEM_PATH_EXISTS,
    FILESYSTEM_READ_TEXT_FILE,
    FILESYSTEM_REPLACE_TEXT_FILE,
    FILESYSTEM_WRITE_TEXT_FILE,
    HEAVY_COMPACTION,
    JsonObject,
    LOG_COMPACTION,
    PAPERCLIP_REQUEST,
    PROMPT_CREATE_SYSTEM_PROMPT,
    REASON_BRAINSTORM,
    REASON_CHAIN_OF_THOUGHT,
    REASON_CRITIQUE,
    REASONING_ABDUCTIVE_REASONING,
    REASONING_ANALOGY_GENERATION,
    REASONING_ASSUMPTION_SURFACING,
    REASONING_BACKCASTING,
    REASONING_BACKWARD_CHAINING,
    REASONING_BIAS_DETECTION,
    REASONING_BLINDSPOT_CHECK,
    REASONING_BOTTLENECK_IDENTIFICATION,
    REASONING_BUTTERFLY_EFFECT_TRACE,
    REASONING_CONFIDENCE_CALIBRATION,
    REASONING_CONSTRAINT_MAPPING,
    REASONING_COST_BENEFIT_ANALYSIS,
    REASONING_CYNEFIN_CATEGORIZATION,
    REASONING_DEVILS_ADVOCATE,
    REASONING_DIALECTICAL_REASONING,
    REASONING_DIVIDE_AND_CONQUER,
    REASONING_FACT_CHECKING,
    REASONING_FALSIFICATION_TEST,
    REASONING_FEEDBACK_LOOP_IDENTIFICATION,
    REASONING_FIRST_PRINCIPLES,
    REASONING_FORWARD_CHAINING,
    REASONING_GRAPH_OF_THOUGHTS,
    REASONING_HYPOTHESIS_GENERATION,
    REASONING_LATERAL_THINKING,
    REASONING_MEANS_END_ANALYSIS,
    REASONING_MORPHOLOGICAL_ANALYSIS,
    REASONING_NETWORK_MAPPING,
    REASONING_PARETO_ANALYSIS,
    REASONING_PERSONA_ADOPTION,
    REASONING_PLAN_AND_SOLVE,
    REASONING_POST_MORTEM,
    REASONING_PRE_MORTEM,
    REASONING_PROVOCATION_OPERATION,
    REASONING_RED_TEAMING,
    REASONING_ROLE_STORMING,
    REASONING_ROOT_CAUSE_ANALYSIS,
    REASONING_SCAMPER,
    REASONING_SCENARIO_PLANNING,
    REASONING_SECOND_ORDER_EFFECTS,
    REASONING_SELF_CRITIQUE,
    REASONING_SIX_THINKING_HATS,
    REASONING_STAKEHOLDER_ANALYSIS,
    REASONING_STEELMANNING,
    REASONING_STEP_BY_STEP,
    REASONING_SWOT_ANALYSIS,
    REASONING_TRADEOFF_EVALUATION,
    REASONING_TREE_OF_THOUGHTS,
    REASONING_TREND_EXTRAPOLATION,
    REASONING_VARIABLE_ISOLATION,
    REASONING_WORST_IDEA_GENERATION,
    RECORDS_COUNT_BY_FIELD,
    RECORDS_FILTER_RECORDS,
    RECORDS_LIMIT_RECORDS,
    RECORDS_SELECT_FIELDS,
    RECORDS_SORT_RECORDS,
    RECORDS_UNIQUE_RECORDS,
    REMOVE_TOOL_RESULTS,
    REMOVE_TOOLS,
    RegisteredTool,
    SEARCH_OR_SUMMARIZE,
    TEXT_NORMALIZE_WHITESPACE,
    TEXT_REGEX_EXTRACT,
    TEXT_TRUNCATE_TEXT,
    ToolArguments,
    ToolCall,
    ToolDefinition,
    ToolHandler,
    ToolResult,
)
from harnessiq.shared.hooks import (
    ApprovalPolicy,
    DEFAULT_APPROVAL_POLICY,
    HookContext,
    HookDefinition,
    HookHandler,
    HookPhase,
    HookResponse,
    RegisteredHook,
)

from .browser import build_browser_tool_definitions, create_browser_tools
from .browser_use import build_browser_use_request_tool_definition, create_browser_use_tools
from .eval import build_evaluate_company_tool_definition, create_evaluate_company_tool
from .builtin import BUILTIN_TOOLS
from .context_compaction import (
    ContextSummarizer,
    apply_log_compaction,
    create_context_compaction_tools,
    heavy_compact_context,
    remove_tool_entries,
    remove_tool_result_entries,
    summarize_and_log_compact,
)
from .context import create_context_tools
from .artifact import ArtifactToolRuntime, create_artifact_tools
from .control import ControlToolRuntime, create_control_tools
from .filesystem import (
    append_text_file,
    copy_path,
    create_filesystem_tools,
    get_current_directory,
    list_directory,
    make_directory,
    path_exists,
    read_text_file,
    replace_text_file,
    write_text_file,
)
from .filesystem_safe import create_filesystem_safe_tools
from .general_purpose import (
    FilterOperator,
    TruncatePosition,
    count_by_field,
    create_general_purpose_tools,
    filter_records,
    limit_records,
    normalize_whitespace,
    pause_for_human,
    regex_extract,
    select_fields,
    sort_records,
    truncate_text,
    unique_records,
)
from .memory import MemoryToolRuntime, create_memory_tools
from .records import create_records_tools
from .runtime_support import DEFAULT_TOOL_RUNTIME_ROOT
from .text import create_text_tools
from .validation import create_validation_tools
from .instagram import create_instagram_tools
from .hooks import (
    create_approval_policy_hook,
    create_default_hook_tools,
    define_hook_tool,
    hook_tool,
    is_tool_allowed,
)
from .paperclip import (
    build_paperclip_request_tool_definition,
    create_paperclip_tools,
)
from .prompting import create_prompt_tools, create_system_prompt
from .paperclip import (
    build_paperclip_request_tool_definition,
    create_paperclip_tools,
)
from .search import build_search_or_summarize_tool_definition, create_search_or_summarize_tool
from .reasoning import (
    brainstorm,
    chain_of_thought,
    create_injectable_reasoning_tools,
    create_reasoning_tools,
    critique,
)
from .reasoning import create_reasoning_tools
from .reasoning.core import brainstorm, chain_of_thought, critique
from .resend import (
    DEFAULT_RESEND_BASE_URL,
    DEFAULT_RESEND_USER_AGENT,
    RESEND_REQUEST,
    ResendClient,
    ResendCredentials,
    ResendOperation,
    ResendPreparedRequest,
    build_resend_operation_catalog,
    build_resend_request_tool_definition,
    create_resend_tools,
    get_resend_operation,
)
from .registry import ToolRegistry, create_builtin_registry, create_tool_registry, merge_tools

__all__ = [
    "ADD_NUMBERS",
    "ApprovalPolicy",
    "BROWSER_CLICK",
    "BROWSER_EXTRACT_CONTENT",
    "BROWSER_FIND_ELEMENT",
    "BROWSER_GET_CURRENT_URL",
    "BROWSER_GET_TEXT",
    "BROWSER_HOVER",
    "BROWSER_NAVIGATE",
    "BROWSER_PRESS_KEY",
    "BROWSER_SCREENSHOT",
    "BROWSER_SCROLL",
    "BROWSER_SELECT_OPTION",
    "BROWSER_TYPE",
    "BROWSER_UPLOAD_FILE",
    "BROWSER_USE_REQUEST",
    "BROWSER_VIEW_HTML",
    "BROWSER_WAIT_FOR_ELEMENT",
    "BUILTIN_TOOLS",
    "CONTROL_PAUSE_FOR_HUMAN",
    "ControlToolRuntime",
    "ContextSummarizer",
    "ArtifactToolRuntime",
    "DEFAULT_TOOL_RUNTIME_ROOT",
    "DEFAULT_APPROVAL_POLICY",
    "DEFAULT_RESEND_BASE_URL",
    "DEFAULT_RESEND_USER_AGENT",
    "ECHO_TEXT",
    "EVALUATE_COMPANY",
    "FILESYSTEM_APPEND_TEXT_FILE",
    "FILESYSTEM_COPY_PATH",
    "FILESYSTEM_GET_CURRENT_DIRECTORY",
    "FILESYSTEM_LIST_DIRECTORY",
    "FILESYSTEM_MAKE_DIRECTORY",
    "FILESYSTEM_PATH_EXISTS",
    "FILESYSTEM_READ_TEXT_FILE",
    "FILESYSTEM_REPLACE_TEXT_FILE",
    "FILESYSTEM_WRITE_TEXT_FILE",
    "create_filesystem_safe_tools",
    "FilterOperator",
    "HEAVY_COMPACTION",
    "HookContext",
    "HookDefinition",
    "HookHandler",
    "HookPhase",
    "HookResponse",
    "JsonObject",
    "LOG_COMPACTION",
    "MemoryToolRuntime",
    "PAPERCLIP_REQUEST",
    "PROMPT_CREATE_SYSTEM_PROMPT",
    "REASON_BRAINSTORM",
    "REASON_CHAIN_OF_THOUGHT",
    "REASON_CRITIQUE",
    "REASONING_ABDUCTIVE_REASONING",
    "REASONING_ANALOGY_GENERATION",
    "REASONING_ASSUMPTION_SURFACING",
    "REASONING_BACKCASTING",
    "REASONING_BACKWARD_CHAINING",
    "REASONING_BIAS_DETECTION",
    "REASONING_BLINDSPOT_CHECK",
    "REASONING_BOTTLENECK_IDENTIFICATION",
    "REASONING_BUTTERFLY_EFFECT_TRACE",
    "REASONING_CONFIDENCE_CALIBRATION",
    "REASONING_CONSTRAINT_MAPPING",
    "REASONING_COST_BENEFIT_ANALYSIS",
    "REASONING_CYNEFIN_CATEGORIZATION",
    "REASONING_DEVILS_ADVOCATE",
    "REASONING_DIALECTICAL_REASONING",
    "REASONING_DIVIDE_AND_CONQUER",
    "REASONING_FACT_CHECKING",
    "REASONING_FALSIFICATION_TEST",
    "REASONING_FEEDBACK_LOOP_IDENTIFICATION",
    "REASONING_FIRST_PRINCIPLES",
    "REASONING_FORWARD_CHAINING",
    "REASONING_GRAPH_OF_THOUGHTS",
    "REASONING_HYPOTHESIS_GENERATION",
    "REASONING_LATERAL_THINKING",
    "REASONING_MEANS_END_ANALYSIS",
    "REASONING_MORPHOLOGICAL_ANALYSIS",
    "REASONING_NETWORK_MAPPING",
    "REASONING_PARETO_ANALYSIS",
    "REASONING_PERSONA_ADOPTION",
    "REASONING_PLAN_AND_SOLVE",
    "REASONING_POST_MORTEM",
    "REASONING_PRE_MORTEM",
    "REASONING_PROVOCATION_OPERATION",
    "REASONING_RED_TEAMING",
    "REASONING_ROLE_STORMING",
    "REASONING_ROOT_CAUSE_ANALYSIS",
    "REASONING_SCAMPER",
    "REASONING_SCENARIO_PLANNING",
    "REASONING_SECOND_ORDER_EFFECTS",
    "REASONING_SELF_CRITIQUE",
    "REASONING_SIX_THINKING_HATS",
    "REASONING_STAKEHOLDER_ANALYSIS",
    "REASONING_STEELMANNING",
    "REASONING_STEP_BY_STEP",
    "REASONING_SWOT_ANALYSIS",
    "REASONING_TRADEOFF_EVALUATION",
    "REASONING_TREE_OF_THOUGHTS",
    "REASONING_TREND_EXTRAPOLATION",
    "REASONING_VARIABLE_ISOLATION",
    "REASONING_WORST_IDEA_GENERATION",
    "RECORDS_COUNT_BY_FIELD",
    "RECORDS_FILTER_RECORDS",
    "RECORDS_LIMIT_RECORDS",
    "RECORDS_SELECT_FIELDS",
    "RECORDS_SORT_RECORDS",
    "RECORDS_UNIQUE_RECORDS",
    "RESEND_REQUEST",
    "REMOVE_TOOL_RESULTS",
    "REMOVE_TOOLS",
    "RegisteredHook",
    "RegisteredTool",
    "SEARCH_OR_SUMMARIZE",
    "ResendClient",
    "ResendCredentials",
    "ResendOperation",
    "ResendPreparedRequest",
    "TEXT_NORMALIZE_WHITESPACE",
    "TEXT_REGEX_EXTRACT",
    "TEXT_TRUNCATE_TEXT",
    "ToolArguments",
    "ToolCall",
    "ToolDefinition",
    "ToolHandler",
    "ToolRegistry",
    "ToolResult",
    "TruncatePosition",
    "append_text_file",
    "apply_log_compaction",
    "build_browser_tool_definitions",
    "build_browser_use_request_tool_definition",
    "build_evaluate_company_tool_definition",
    "build_paperclip_request_tool_definition",
    "build_resend_operation_catalog",
    "build_resend_request_tool_definition",
    "build_search_or_summarize_tool_definition",
    "copy_path",
    "count_by_field",
    "create_approval_policy_hook",
    "create_browser_tools",
    "create_browser_use_tools",
    "create_builtin_registry",
    "create_artifact_tools",
    "create_control_tools",
    "create_context_tools",
    "create_tool_registry",
    "create_context_compaction_tools",
    "create_default_hook_tools",
    "create_filesystem_tools",
    "create_general_purpose_tools",
    "create_instagram_tools",
    "create_memory_tools",
    "create_paperclip_tools",
    "create_evaluate_company_tool",
    "create_records_tools",
    "brainstorm",
    "chain_of_thought",
    "create_injectable_reasoning_tools",
    "create_paperclip_tools",
    "create_prompt_tools",
    "create_reasoning_tools",
    "create_resend_tools",
    "create_search_or_summarize_tool",
    "create_text_tools",
    "create_validation_tools",
    "critique",
    "create_system_prompt",
    "define_hook_tool",
    "filter_records",
    "get_current_directory",
    "get_resend_operation",
    "heavy_compact_context",
    "limit_records",
    "list_directory",
    "make_directory",
    "merge_tools",
    "normalize_whitespace",
    "path_exists",
    "pause_for_human",
    "read_text_file",
    "replace_text_file",
    "regex_extract",
    "remove_tool_entries",
    "remove_tool_result_entries",
    "select_fields",
    "sort_records",
    "summarize_and_log_compact",
    "truncate_text",
    "unique_records",
    "hook_tool",
    "is_tool_allowed",
    "write_text_file",
]
