"""Public interface contracts for runtime dependency seams."""

from __future__ import annotations

from .cli import FactoryLoader, IterableFactory, IterableFactoryLoader, PreparedStoreLoader, ZeroArgumentFactory
from .output_sinks import (
    ConfluenceSinkClient,
    GoogleSheetsSinkClient,
    LinearSinkClient,
    MongoClientFactory,
    MongoCollectionSinkClient,
    NotionSinkClient,
    SupabaseSinkClient,
    WebhookSinkClient,
)
from .provider_clients import (
    PreparedRequest,
    ProviderClientBuilder,
    RequestExecutor,
    RequestPreparingClient,
    ResendRequestClient,
    TimeoutConfig,
)
from .tool_selection import DynamicToolSelector, EmbeddingBackend, EmbeddingModelClient
from .models import AnthropicModelClient, GeminiModelClient, OpenAIStyleModelClient
from .formalization import (
    ArtifactSpec,
    BaseArtifactLayer,
    BaseContractLayer,
    BaseFormalizationLayer,
    BaseHookLayer,
    BaseRoleLayer,
    BaseStageLayer,
    BaseStateLayer,
    BaseToolContributionLayer,
    BudgetSpec,
    FieldSpec,
    FormalizationDescription,
    FormalizationEnforcementType,
    FormalizationHookName,
    HookBehaviorSpec,
    LayerRuleRecord,
    RoleSpec,
    StageSpec,
    StateFieldSpec,
    StateUpdateRule,
)

__all__ = [
    "AnthropicModelClient",
    "ArtifactSpec",
    "BaseArtifactLayer",
    "BaseContractLayer",
    "BaseFormalizationLayer",
    "BaseHookLayer",
    "BaseRoleLayer",
    "BaseStageLayer",
    "BaseStateLayer",
    "BaseToolContributionLayer",
    "BudgetSpec",
    "ConfluenceSinkClient",
    "DynamicToolSelector",
    "EmbeddingBackend",
    "EmbeddingModelClient",
    "FactoryLoader",
    "FieldSpec",
    "FormalizationDescription",
    "FormalizationEnforcementType",
    "FormalizationHookName",
    "GeminiModelClient",
    "GoogleSheetsSinkClient",
    "HookBehaviorSpec",
    "IterableFactory",
    "IterableFactoryLoader",
    "LayerRuleRecord",
    "LinearSinkClient",
    "MongoClientFactory",
    "MongoCollectionSinkClient",
    "NotionSinkClient",
    "OpenAIStyleModelClient",
    "PreparedRequest",
    "PreparedStoreLoader",
    "ProviderClientBuilder",
    "RequestExecutor",
    "RequestPreparingClient",
    "ResendRequestClient",
    "RoleSpec",
    "StageSpec",
    "StateFieldSpec",
    "StateUpdateRule",
    "SupabaseSinkClient",
    "TimeoutConfig",
    "WebhookSinkClient",
    "ZeroArgumentFactory",
]
