"""Public interface contracts for runtime dependency seams."""

from __future__ import annotations

from .cli import FactoryLoader, IterableFactory, IterableFactoryLoader, PreparedStoreLoader, ZeroArgumentFactory
from .output_sinks import (
    ConfluenceSinkClient,
    GoogleSheetsSinkClient,
    LinearSinkClient,
    MongoClientFactory,
    MongoCollectionSinkClient,
    NotionSinkClient,
    SupabaseSinkClient,
    WebhookSinkClient,
)
from .provider_clients import (
    PreparedRequest,
    ProviderClientBuilder,
    RequestExecutor,
    RequestPreparingClient,
    ResendRequestClient,
    TimeoutConfig,
)
from .tool_selection import DynamicToolSelector, EmbeddingBackend, EmbeddingModelClient
from .models import AnthropicModelClient, GeminiModelClient, OpenAIStyleModelClient
from .formalization import (
    ArtifactSpec,
    ArtifactNotFoundError,
    BaseArtifactLayer,
    BaseContractLayer,
    BaseFormalizationLayer,
    BaseHookLayer,
    BaseRoleLayer,
    BaseStageLayer,
    BaseStateLayer,
    BaseToolContributionLayer,
    BudgetSpec,
    CompletionRequirement,
    FieldSpec,
    FORMAT_EXTENSION_MAP,
    FORMAT_TOOL_MAP,
    FormalizationDescription,
    FormalizationEnforcementType,
    FormalizationHookName,
    HookBehaviorSpec,
    InjectionPolicy,
    InputArtifactLayer,
    InputArtifactSpec,
    LayerRuleRecord,
    OnOversize,
    OutputArtifactMissingError,
    OutputArtifactSpec,
    RoleSpec,
    SupportedInputFormat,
    SupportedOutputFormat,
    resolve_artifact_path,
    resolve_output_path,
    resolve_write_tool_key,
    StageSpec,
    StateFieldSpec,
    StateUpdateRule,
    validate_input_artifact_specs,
    validate_output_artifact_specs,
)

__all__ = [
    "AnthropicModelClient",
    "ArtifactSpec",
    "ArtifactNotFoundError",
    "BaseArtifactLayer",
    "BaseContractLayer",
    "BaseFormalizationLayer",
    "BaseHookLayer",
    "BaseRoleLayer",
    "BaseStageLayer",
    "BaseStateLayer",
    "BaseToolContributionLayer",
    "BudgetSpec",
    "CompletionRequirement",
    "ConfluenceSinkClient",
    "DynamicToolSelector",
    "EmbeddingBackend",
    "EmbeddingModelClient",
    "FactoryLoader",
    "FieldSpec",
    "FORMAT_EXTENSION_MAP",
    "FORMAT_TOOL_MAP",
    "FormalizationDescription",
    "FormalizationEnforcementType",
    "FormalizationHookName",
    "GeminiModelClient",
    "GoogleSheetsSinkClient",
    "HookBehaviorSpec",
    "InjectionPolicy",
    "InputArtifactLayer",
    "InputArtifactSpec",
    "IterableFactory",
    "IterableFactoryLoader",
    "LayerRuleRecord",
    "LinearSinkClient",
    "MongoClientFactory",
    "MongoCollectionSinkClient",
    "NotionSinkClient",
    "OpenAIStyleModelClient",
    "OnOversize",
    "OutputArtifactMissingError",
    "OutputArtifactSpec",
    "PreparedRequest",
    "PreparedStoreLoader",
    "ProviderClientBuilder",
    "RequestExecutor",
    "RequestPreparingClient",
    "resolve_artifact_path",
    "resolve_output_path",
    "resolve_write_tool_key",
    "ResendRequestClient",
    "RoleSpec",
    "StageSpec",
    "StateFieldSpec",
    "StateUpdateRule",
    "SupportedInputFormat",
    "SupportedOutputFormat",
    "SupabaseSinkClient",
    "TimeoutConfig",
    "validate_input_artifact_specs",
    "validate_output_artifact_specs",
    "WebhookSinkClient",
    "ZeroArgumentFactory",
]
from importlib import import_module
from typing import Any

_SYMBOL_TO_MODULE = {
    "AnthropicModelClient": "models",
    "ArtifactSpec": "formalization",
    "ArtifactNotFoundError": "formalization",
    "BaseArtifactLayer": "formalization",
    "BaseContractLayer": "formalization",
    "BaseFormalizationLayer": "formalization",
    "BaseHookLayer": "formalization",
    "BaseRoleLayer": "formalization",
    "BaseStageLayer": "formalization",
    "BaseStateLayer": "formalization",
    "BaseToolContributionLayer": "formalization",
    "BudgetSpec": "formalization",
    "CompletionRequirement": "formalization",
    "ConfluenceSinkClient": "output_sinks",
    "DynamicToolSelector": "tool_selection",
    "EmbeddingBackend": "tool_selection",
    "EmbeddingModelClient": "tool_selection",
    "FactoryLoader": "cli",
    "FieldSpec": "formalization",
    "FORMAT_EXTENSION_MAP": "formalization",
    "FORMAT_TOOL_MAP": "formalization",
    "FormalizationDescription": "formalization",
    "FormalizationEnforcementType": "formalization",
    "FormalizationHookName": "formalization",
    "GeminiModelClient": "models",
    "GoogleSheetsSinkClient": "output_sinks",
    "HookBehaviorSpec": "formalization",
    "InjectionPolicy": "formalization",
    "InputArtifactLayer": "formalization",
    "InputArtifactSpec": "formalization",
    "IterableFactory": "cli",
    "IterableFactoryLoader": "cli",
    "LayerRuleRecord": "formalization",
    "LinearSinkClient": "output_sinks",
    "MongoClientFactory": "output_sinks",
    "MongoCollectionSinkClient": "output_sinks",
    "NotionSinkClient": "output_sinks",
    "OpenAIStyleModelClient": "models",
    "OnOversize": "formalization",
    "OutputArtifactMissingError": "formalization",
    "OutputArtifactSpec": "formalization",
    "PreparedRequest": "provider_clients",
    "PreparedStoreLoader": "cli",
    "ProviderClientBuilder": "provider_clients",
    "RequestExecutor": "provider_clients",
    "RequestPreparingClient": "provider_clients",
    "resolve_artifact_path": "formalization",
    "resolve_output_path": "formalization",
    "resolve_write_tool_key": "formalization",
    "ResendRequestClient": "provider_clients",
    "RoleSpec": "formalization",
    "StageSpec": "formalization",
    "StateFieldSpec": "formalization",
    "SupportedInputFormat": "formalization",
    "SupportedOutputFormat": "formalization",
    "SupabaseSinkClient": "output_sinks",
    "TimeoutConfig": "provider_clients",
    "validate_input_artifact_specs": "formalization",
    "validate_output_artifact_specs": "formalization",
    "WebhookSinkClient": "output_sinks",
    "ZeroArgumentFactory": "cli",
}

__all__ = sorted(_SYMBOL_TO_MODULE)


def __getattr__(name: str) -> Any:
    module_name = _SYMBOL_TO_MODULE.get(name)
    if module_name is None:
        raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
    module = import_module(f"{__name__}.{module_name}")
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted([*globals(), *__all__])
