"""
===============================================================================
File: harnessiq/formalization/__init__.py

What this file does:
- Defines the package-level export surface for `harnessiq/formalization` within
  the HarnessIQ runtime.
- Public formalization-layer contracts and runtime building blocks.

Use cases:
- Import ArtifactSpec, ArtifactNotFoundError, BaseArtifactLayer,
  BaseBehaviorLayer, BaseExecutionPaceLayer, BaseErrorRecoveryLayer from one
  stable package entry point.
- Read this module to understand what `harnessiq/formalization` intends to
  expose publicly.

How to use it:
- Import from `harnessiq/formalization` when you want the supported facade
  instead of reaching through deeper internal modules.

Intent:
- Keep the public surface for `harnessiq/formalization` explicit, discoverable,
  and easier to maintain.
===============================================================================
"""

from .artifacts import (
    ArtifactNotFoundError,
    CompletionRequirement,
    FORMAT_EXTENSION_MAP,
    FORMAT_TOOL_MAP,
    InjectionPolicy,
    InputArtifactLayer,
    InputArtifactSpec,
    OnOversize,
    OutputArtifactMissingError,
    OutputArtifactLayer,
    OutputArtifactSpec,
    SupportedInputFormat,
    SupportedOutputFormat,
    resolve_artifact_path,
    resolve_output_path,
    resolve_write_tool_key,
    validate_input_artifact_specs,
    validate_output_artifact_specs,
)
from .behaviors import (
    BaseBehaviorLayer,
    BaseExecutionPaceLayer,
    BaseErrorRecoveryLayer,
    BaseQualityBehaviorLayer,
    BaseReasoningBehaviorLayer,
    BaseSafetyBehaviorLayer,
    BaseToolBehaviorLayer,
    BehaviorConstraint,
    BehaviorEnforcementMode,
    BehaviorViolationAction,
    CitationRequirementBehavior,
    ErrorEscalationBehavior,
    GuardrailSpec,
    HypothesisTestingBehavior,
    IrreversibleActionGateBehavior,
    PaceRuleSpec,
    PreActionReasoningBehavior,
    ProgressCheckpointBehavior,
    QualityCriterionSpec,
    QualityGateBehavior,
    RateLimitBehavior,
    RecoveryStrategySpec,
    ReflectionCadenceBehavior,
    ReasoningRequirementSpec,
    RetryStrategyBehavior,
    ScopeEnforcementBehavior,
    ScopeGuardBehavior,
    SelfCritiqueBehavior,
    StuckDetectionBehavior,
    ToolCallLimitBehavior,
    ToolConstraintSpec,
    ToolCooldownBehavior,
    ToolSequencingBehavior,
    VerificationBehavior,
)
from .base import (
    ArtifactSpec,
    BaseArtifactLayer,
    BaseContractLayer,
    BaseFormalizationLayer,
    BaseHookLayer,
    BaseRoleLayer,
    BaseStageLayer,
    BaseStateLayer,
    BaseToolContributionLayer,
    BudgetSpec,
    FieldSpec,
    FormalizationDescription,
    FormalizationEnforcementType,
    FormalizationHookName,
    HookBehaviorSpec,
    LayerRuleRecord,
    RoleSpec,
    StageSpec,
    StateFieldSpec,
)

__all__ = [
    "ArtifactSpec",
    "ArtifactNotFoundError",
    "BaseArtifactLayer",
    "BaseBehaviorLayer",
    "BaseExecutionPaceLayer",
    "BaseErrorRecoveryLayer",
    "BaseQualityBehaviorLayer",
    "BaseReasoningBehaviorLayer",
    "BaseSafetyBehaviorLayer",
    "BaseContractLayer",
    "BaseFormalizationLayer",
    "BaseHookLayer",
    "BaseRoleLayer",
    "BaseStageLayer",
    "BaseStateLayer",
    "BaseToolBehaviorLayer",
    "BaseToolContributionLayer",
    "BudgetSpec",
    "CompletionRequirement",
    "BehaviorConstraint",
    "BehaviorEnforcementMode",
    "BehaviorViolationAction",
    "CitationRequirementBehavior",
    "ErrorEscalationBehavior",
    "FORMAT_EXTENSION_MAP",
    "FORMAT_TOOL_MAP",
    "FieldSpec",
    "FormalizationDescription",
    "FormalizationEnforcementType",
    "FormalizationHookName",
    "GuardrailSpec",
    "HookBehaviorSpec",
    "InjectionPolicy",
    "InputArtifactLayer",
    "InputArtifactSpec",
    "LayerRuleRecord",
    "OnOversize",
    "OutputArtifactMissingError",
    "OutputArtifactLayer",
    "OutputArtifactSpec",
    "HypothesisTestingBehavior",
    "IrreversibleActionGateBehavior",
    "PaceRuleSpec",
    "PreActionReasoningBehavior",
    "ProgressCheckpointBehavior",
    "QualityCriterionSpec",
    "QualityGateBehavior",
    "RateLimitBehavior",
    "RecoveryStrategySpec",
    "ReflectionCadenceBehavior",
    "ReasoningRequirementSpec",
    "RetryStrategyBehavior",
    "RoleSpec",
    "ScopeEnforcementBehavior",
    "ScopeGuardBehavior",
    "SelfCritiqueBehavior",
    "StageSpec",
    "StateFieldSpec",
    "StuckDetectionBehavior",
    "SupportedInputFormat",
    "SupportedOutputFormat",
    "ToolCallLimitBehavior",
    "ToolConstraintSpec",
    "ToolCooldownBehavior",
    "ToolSequencingBehavior",
    "VerificationBehavior",
    "resolve_artifact_path",
    "resolve_output_path",
    "resolve_write_tool_key",
    "validate_input_artifact_specs",
    "validate_output_artifact_specs",
]
