"""Shared DTO package for explicit layer-boundary contracts."""

from .agents import (
    AgentInstancePayload,
    ApolloAgentRequest,
    EmailAgentRequest,
    ExaOutreachAgentInstancePayload,
    ExaAgentRequest,
    InstagramAgentInstancePayload,
    InstantlyAgentRequest,
    KnowtAgentInstancePayload,
    LeadsAgentInstancePayload,
    LinkedInAgentInstancePayload,
    OutreachAgentRequest,
    ProspectingAgentInstancePayload,
    ProviderToolAgentRequest,
    ResearchSweepAgentInstancePayload,
    StatelessAgentInstancePayload,
)
from .cli import (
    HarnessAdapterResponseDTO,
    HarnessCommandPayloadDTO,
    HarnessParameterBundleDTO,
    HarnessProfileDTO,
    HarnessProfileIndexDTO,
    HarnessProfileIndexRecordDTO,
    HarnessProfileViewDTO,
    HarnessResumePayloadDTO,
    HarnessRunResultDTO,
    HarnessRunSnapshotDTO,
    HarnessRunSummaryDTO,
    HarnessStatePayloadDTO,
)
from .providers import (
    ArxivOperationResultDTO,
    PreparedProviderOperationResultDTO,
    ProviderOperationRequestDTO,
    ProviderPayloadRequestDTO,
    ProviderPayloadResultDTO,
)
from .base import SerializableDTO, coerce_serializable_mapping
from .prompt_harnesses import (
    MissionDrivenInstancePayload,
    SpawnSpecializedSubagentsInstancePayload,
    SubAgentAssignmentDTO,
    WorkerExecutionResultDTO,
)

__all__ = [
    "AgentInstancePayload",
    "ApolloAgentRequest",
    "EmailAgentRequest",
    "ExaOutreachAgentInstancePayload",
    "ExaAgentRequest",
    "InstagramAgentInstancePayload",
    "InstantlyAgentRequest",
    "ArxivOperationResultDTO",
    "HarnessAdapterResponseDTO",
    "HarnessCommandPayloadDTO",
    "HarnessParameterBundleDTO",
    "HarnessProfileDTO",
    "HarnessProfileIndexDTO",
    "HarnessProfileIndexRecordDTO",
    "HarnessProfileViewDTO",
    "HarnessResumePayloadDTO",
    "HarnessRunResultDTO",
    "HarnessRunSnapshotDTO",
    "HarnessRunSummaryDTO",
    "HarnessStatePayloadDTO",
    "KnowtAgentInstancePayload",
    "LeadsAgentInstancePayload",
    "LinkedInAgentInstancePayload",
    "OutreachAgentRequest",
    "PreparedProviderOperationResultDTO",
    "ProspectingAgentInstancePayload",
    "ProviderOperationRequestDTO",
    "ProviderPayloadRequestDTO",
    "ProviderPayloadResultDTO",
    "ProviderToolAgentRequest",
    "ResearchSweepAgentInstancePayload",
    "MissionDrivenInstancePayload",
    "SerializableDTO",
    "SpawnSpecializedSubagentsInstancePayload",
    "StatelessAgentInstancePayload",
    "SubAgentAssignmentDTO",
    "WorkerExecutionResultDTO",
    "coerce_serializable_mapping",
]
