"""Canonical tool primitives for HarnessHub."""

from src.shared.tools import (
    ADD_NUMBERS,
    CONTROL_PAUSE_FOR_HUMAN,
    ECHO_TEXT,
    HEAVY_COMPACTION,
    JsonObject,
    LOG_COMPACTION,
    RECORDS_COUNT_BY_FIELD,
    RECORDS_FILTER_RECORDS,
    RECORDS_LIMIT_RECORDS,
    RECORDS_SELECT_FIELDS,
    RECORDS_SORT_RECORDS,
    RECORDS_UNIQUE_RECORDS,
    REMOVE_TOOL_RESULTS,
    REMOVE_TOOLS,
    RegisteredTool,
    TEXT_NORMALIZE_WHITESPACE,
    TEXT_REGEX_EXTRACT,
    TEXT_TRUNCATE_TEXT,
    ToolArguments,
    ToolCall,
    ToolDefinition,
    ToolHandler,
    ToolResult,
)

from .builtin import BUILTIN_TOOLS
from .context_compaction import (
    ContextSummarizer,
    apply_log_compaction,
    create_context_compaction_tools,
    heavy_compact_context,
    remove_tool_entries,
    remove_tool_result_entries,
    summarize_and_log_compact,
)
from .general_purpose import (
    FilterOperator,
    TruncatePosition,
    count_by_field,
    create_general_purpose_tools,
    filter_records,
    limit_records,
    normalize_whitespace,
    pause_for_human,
    regex_extract,
    select_fields,
    sort_records,
    truncate_text,
    unique_records,
)
from .registry import ToolRegistry, create_builtin_registry

__all__ = [
    "ADD_NUMBERS",
    "BUILTIN_TOOLS",
    "CONTROL_PAUSE_FOR_HUMAN",
    "ContextSummarizer",
    "ECHO_TEXT",
    "FilterOperator",
    "HEAVY_COMPACTION",
    "JsonObject",
    "LOG_COMPACTION",
    "RECORDS_COUNT_BY_FIELD",
    "RECORDS_FILTER_RECORDS",
    "RECORDS_LIMIT_RECORDS",
    "RECORDS_SELECT_FIELDS",
    "RECORDS_SORT_RECORDS",
    "RECORDS_UNIQUE_RECORDS",
    "REMOVE_TOOL_RESULTS",
    "REMOVE_TOOLS",
    "RegisteredTool",
    "TEXT_NORMALIZE_WHITESPACE",
    "TEXT_REGEX_EXTRACT",
    "TEXT_TRUNCATE_TEXT",
    "ToolArguments",
    "ToolCall",
    "ToolDefinition",
    "ToolHandler",
    "ToolRegistry",
    "ToolResult",
    "TruncatePosition",
    "apply_log_compaction",
    "count_by_field",
    "create_builtin_registry",
    "create_context_compaction_tools",
    "create_general_purpose_tools",
    "filter_records",
    "heavy_compact_context",
    "limit_records",
    "normalize_whitespace",
    "pause_for_human",
    "regex_extract",
    "remove_tool_entries",
    "remove_tool_result_entries",
    "select_fields",
    "sort_records",
    "summarize_and_log_compact",
    "truncate_text",
    "unique_records",
]
